BASE_TASK_CONFIG_PATH: "configs/tasks/multinav_cyl_3ON_semantic.yaml"
TRAINER_NAME: "semantic"
ENV_NAME: "NavRLEnv"
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
VIDEO_OPTION: []
TENSORBOARD_DIR: "experiments/3on2.0/semantic/train"
TENSORBOARD_DIR_EVAL: "experiments/3on2.0/semantic/eval"
VIDEO_DIR: "experiments/3on2.0/semantic/eval/videos"
TEST_EPISODE_COUNT: 5
EVAL_CKPT_PATH_DIR: "experiments/3on2.0/semantic/checkpoints"
NUM_PROCESSES: 12
NUM_ENVIRONMENTS: 12
SENSORS: ["RGB_SENSOR", "DEPTH_SENSOR", "SEMANTIC_SENSOR"]
CHECKPOINT_FOLDER: "experiments/3on2.0/semantic/checkpoints"
NUM_UPDATES: 10000
LOG_INTERVAL: 1
CHECKPOINT_INTERVAL: 500

EVAL:
  SPLIT: "train"

RL:
  SUCCESS_REWARD: 3.0
  SUBSUCCESS_REWARD: 3.0
  SLACK_REWARD: -0.001
  FALSE_FOUND_PENALTY: False
  FALSE_FOUND_PENALTY_VALUE: 2.5
  OBJECT_CATEGORY_EMBEDDING_SIZE: 32
  PREVIOUS_ACTION_EMBEDDING_SIZE: 32
  PREVIOUS_ACTION: True
  PPO:
    # ppo params
    clip_param: 0.2
    ppo_epoch: 4
    num_mini_batch: 2
    value_loss_coef: 0.5
    entropy_coef: 0.01
    semantic_map_loss_coef: 0.01
    next_goal_map_loss_coef: 0.01
    lr: 2.5e-4
    eps: 1e-5
    max_grad_norm: 0.2
    num_steps: 64
    use_gae: True
    gamma: 0.99
    tau: 0.95
    use_linear_clip_decay: True
    use_linear_lr_decay: True
    reward_window_size: 50
    use_normalized_advantage: False
    hidden_size: 768
  MAPS:
    egocentric_map_size: 13 # 3 x 3
    global_map_size: 275
    global_map_depth: 32
    coordinate_min: -62.3241
    coordinate_max: 90.0399
    USE_OCCUPANCY: False
    linear_out: 512
    num_classes: 10
    visual_encoder_type: "rednet" # one of "fasterrcnn", "rednet", "simple"
