ENVIRONMENT:
  MAX_EPISODE_STEPS: 2500
SIMULATOR:
  TURN_ANGLE: 30
  TILT_ANGLE: 30
  ACTION_SPACE_CONFIG: "v1"
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
    HEIGHT: 0.88
    RADIUS: 0.1
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: False
  SEMANTIC_SENSOR:
    WIDTH: 256
    HEIGHT: 256
    HFOV: 79
    POSITION: [0, 0.88, 0]
  RGB_SENSOR:
    WIDTH: 256
    HEIGHT: 256
    HFOV: 79
    POSITION: [0, 0.88, 0]
  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
    HFOV: 79
    POSITION: [0, 0.88, 0]
TASK:
  TYPE: MultiObjectNav-v1
  CYL_OBJECTS_PATH: "data/multion_cyl_objects"
  OBJECTS_TYPE: "CYL"
  
  POSSIBLE_ACTIONS: ["FOUND", "MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT"]

  SUCCESS_DISTANCE: 1.0

  SENSORS: ['MULTI_OBJECT_GOAL_SENSOR', 'COMPASS_SENSOR', 'GPS_SENSOR']

  GOAL_SENSOR_UUID: multiobjectgoal

  MEASUREMENTS: ['DISTANCE_TO_GOAL','DISTANCE_TO_CURRENT_OBJECT_GOAL', 'CURRENT_GOAL_SUCCESS', 'PROGRESS', 'MULTION_SUCCESS', 'MULTION_PPL', 'MULTION_SPL']
  SUCCESS:
    SUCCESS_DISTANCE: 1.0
  DISTANCE_TO_GOAL:
    DISTANCE_TO: POINT

DATASET:
  TYPE: MultiObjectNav-v1
  SPLIT: train
  SCENES_DIR: "data/scene_datasets/"
  DATA_PATH: "data/5_ON_CYL_{split}/{split}/{split}.json.gz"